### PR TITLE
Fix crash in transport window when nothing is selected

### LINKED ISSUE #1300: S2 crashes in transport order settings
When pressing the up/down-Buttons in the transport order settings while no goods are chosen, the client crashes:

`terminate called after throwing an instance of 'std::logic_error'
  what():  No button selected in option group`

-> should be catched

Used version: v20200905 24b1e7

### PR DESCRIPTION
**Pull request by Flamefire**
Select the first button on creation, fixes #1300
Also some refactoring to unify the arrays

### CODE REVIEW

File: libs/s25main/ingameWindows/iwTransport.cpp [hunk 1]
```diff
@@ -53,42 +48,44 @@ iwTransport::iwTransport(const GameWorldViewer& gwv, GameCommandFactory& gcFacto
...
-    TRANSPORT_SPRITES[6] = LOADER.GetMapTexN(2250 + GD_COAL);
-    TRANSPORT_SPRITES[7] = LOADER.GetMapTexN(2250 + GD_BOARDS);
-    TRANSPORT_SPRITES[8] = LOADER.GetMapTexN(2250 + GD_STONES);
-    TRANSPORT_SPRITES[9] = LOADER.GetMapTexN(2250 + GD_WOOD);
-    TRANSPORT_SPRITES[10] = LOADER.GetMapTexN(2250 + GD_WATER);
-    TRANSPORT_SPRITES[11] = LOADER.GetTextureN("io", 80);
-    TRANSPORT_SPRITES[12] = LOADER.GetMapTexN(2250 + GD_HAMMER);
-    TRANSPORT_SPRITES[13] = LOADER.GetMapTexN(2250 + GD_BOAT);
-
+    buttonData = {{{LOADER.GetMapTexN(2250 + GD_COINS), WARE_NAMES[GD_COINS]},
```
Comment (Flow86) [inline libs/s25main/ingameWindows/iwTransport.cpp:51]: WARE_NAMES is still gettext_noop?

File: libs/s25main/ingameWindows/iwTransport.h [hunk 2]
```diff
@@ -28,9 +29,15 @@ class GameCommandFactory;
...
+    struct ButtonData
+    {
+        ITexture* sprite;
+        std::string tooltip;
+    };
     const GameWorldViewer& gwv;
     GameCommandFactory& gcFactory;
-    ITexture* TRANSPORT_SPRITES[14]; /// Einzelne Bilder für die Waren.
+
+    std::array<ButtonData, 14> buttonData;
```
Comment (Flow86) [inline libs/s25main/ingameWindows/iwTransport.h:40]: can we have a constant for the 14?

**Review by Flow86 — CHANGES_REQUESTED** [review]

File: libs/s25main/ingameWindows/iwTransport.h (hunk 2 above)
Comment (Flow86) [reply libs/s25main/ingameWindows/iwTransport.h:40]: (numButtons?)

File: libs/s25main/ingameWindows/iwTransport.cpp (hunk 1 above)
Comment (Flamefire) [reply libs/s25main/ingameWindows/iwTransport.cpp:51]: Yes, see libs/s25main/gameTypes/GoodTypes.h

I just wanted to avoid copying all the texts here

File: libs/s25main/ingameWindows/iwTransport.h (hunk 2 above)
Comment (Flamefire) [reply libs/s25main/ingameWindows/iwTransport.h:40]: I did it the other way round: Using `buttonData.size` as `numButtons`, which IMO makes more sense: https://github.com/Return-To-The-Roots/s25client/pull/1301/files#diff-b140bedff094aa8fd2769a0841d341a4R66

But actually we should use `TransportOrders.size`... Adding a commit

File: libs/s25main/ingameWindows/iwTransport.cpp (hunk 1 above)
Comment (Flow86) [reply libs/s25main/ingameWindows/iwTransport.cpp:51]: okay, only wanted to make sure that this is not the only place where these are translated :-D

File: libs/s25main/ingameWindows/iwTransport.cpp [hunk 3]
```diff
@@ -53,42 +48,43 @@ iwTransport::iwTransport(const GameWorldViewer& gwv, GameCommandFactory& gcFacto
...
+                   {LOADER.GetTextureN("io", 111), gettext_noop("Weapons")},
+                   {LOADER.GetMapTexN(2250 + GD_BEER), WARE_NAMES[GD_BEER]},
```
Comment (Flow86) [inline libs/s25main/ingameWindows/iwTransport.cpp:53]: do we get an name for the 2250 here?

File: libs/s25main/ingameWindows/iwTransport.cpp [hunk 4]
```diff
@@ -131,13 +127,11 @@ void iwTransport::Msg_ButtonClick(const unsigned ctrl_id)
...
 
-            //// Tooltips in der der Standardbelegung
-            // memcpy(tooltip_indices,STD_TOOLTIP_INDICES,14*sizeof(unsigned short));
-
-            for(unsigned char i = 0; i < 14; ++i)
+            for(unsigned char i = 0; i < buttonData.size(); ++i)
             {
-                group->GetCtrl<ctrlImageButton>(i)->SetImage(TRANSPORT_SPRITES[i]);
-                group->GetCtrl<ctrlImageButton>(i)->SetTooltip(_(TOOLTIPS[i]));
+                const auto& data = buttonData[i];
```
Comment (Flow86) [inline libs/s25main/ingameWindows/iwTransport.cpp:132]: its a pity that you can't get the auto-loop-index somehow :-D (on `for(x : list)`)

Comment (Flamefire) [reply libs/s25main/ingameWindows/iwTransport.cpp:132]: Hm, you can: boost::adapters::indexed IIRC :)

Comment (Flow86) [reply libs/s25main/ingameWindows/iwTransport.cpp:132]: so we could do this instead there? :-D

Comment (Flamefire) [reply libs/s25main/ingameWindows/iwTransport.cpp:132]: I was thinking about it (used it before), but what I really dislike about it (or Boost.Range) is that it is still using C++98. Checked that header and it has includes to Boost.Tuple and Boost.MPL, both are heavy IIRC. And then there is this:

```
// Why yet another "pair" class:
// - std::pair can't store references
```

Which isn't correct. So well, for the sake of compiletimes I'd rather not use it

File: libs/s25main/ingameWindows/iwTransport.cpp (hunk 3 above)
Comment (Flamefire) [reply libs/s25main/ingameWindows/iwTransport.cpp]: > WARES_TEX_MAP_OFFSET

File: libs/s25main/ingameWindows/iwTransport.cpp (hunk 4 above)
Comment (Flow86) [reply libs/s25main/ingameWindows/iwTransport.cpp:132]: yes that makes sense

File: libs/s25main/ingameWindows/iwTransport.cpp (hunk 3 above)
Comment (Flow86) [reply libs/s25main/ingameWindows/iwTransport.cpp]: perfect :-)

**Review by Flow86 — APPROVED** [review]
