### PR TITLE
Custom nations are lowercase -> Fix loading code

### LINKED ISSUE #1420: Babylonian files wrongly named
On Linux, files need exact casing. Currently the babylonian files are called bab_icon.lst, bab_z.lst and wbab_z.lst. They need be written in with capital letters: BAB_ICON.LST BAB_Z.LST, WBAB_Z.LST

See: https://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=272&start=-1#last

### PR DESCRIPTION
**Pull request by Flamefire**
Fixes #1420

Instead of renaming our new files to UPPERCASE I created code to detect the lower case filenames which IMO is nicer as e.g. our resource IDs are lowercase and most other resources are too.

Factored out into a new function for clarity

### CODE REVIEW

File: libs/s25main/Loader.cpp [hunk 1]
```diff
@@ -343,6 +343,38 @@ void Loader::LoadDummyGUIFiles()
...
+{
+    const auto shortName = std::string(NationNames[nation], 0, 3);
+    auto buildingsFilename = shortName + "_Z.LST";
+    auto iconsFilename = shortName + "_ICON.LST";
+    if(isWinter)
+        buildingsFilename.insert(buildingsFilename.begin(), 'W');
+    bfs::path nationFolder;
+    if(rttr::enum_cast(nation) < NUM_NATIVE_NATIONS)
+    {
+        nationFolder = config.ExpandPath(s25::folders::mbob);
```
Comment (Flow86) [inline libs/s25main/Loader.cpp:362]: perhaps some note (=comment) here why we do this differentation

Comment (Flamefire) [reply libs/s25main/Loader.cpp:362]: What would you write here?
IMO the code is clean enough: For native nations use 1 folder and uppercase names and for non-native use another folder and lowercase names.
Can you make a suggestion (i.e. from a readers perspective)?

Comment (Flow86) [reply libs/s25main/Loader.cpp:362]: `For native nations we use uppercase names and for non-native ("new" ones) we use lowercase names.`

**Review by Flow86 — APPROVED** [review]

File: libs/s25main/Loader.cpp [hunk 2]
```diff
@@ -357,6 +357,8 @@ NationResourcesSource getNationResourcesSource(const Nation nation, bool isWinte
     if(isWinter)
         buildingsFilename.insert(buildingsFilename.begin(), 'W');
     bfs::path nationFolder;
+    // The original ("native") nations ise uppercase file names while we use lowercase names for the new ones
```
Comment (Flow86) [inline libs/s25main/Loader.cpp:360]: typo:
```suggestion
    // The original ("native") nations use uppercase file names while we use lowercase names for the new ones
```
