### PR TITLE
Fix BQ update in AI map

### LINKED ISSUE #1127: Assertion failure in SimpleFindPosition
```
Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x0000000000769a4c in AIJH::AIPlayerJH::SimpleFindPosition (this=0x128f1f0, pt=..., 
    size=BQ_CASTLE, radius=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:1025
1025	/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x0000000000769a4c in AIJH::AIPlayerJH::SimpleFindPosition (this=0x128f1f0, pt=..., size=BQ_CASTLE, radius=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:1025
#1  0x0000000000769e49 in AIJH::AIPlayerJH::FindPositionForBuildingAround (this=0x128f1f0, type=BLD_PIGFARM, around=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:1051
#2  0x000000000077c6dd in AIJH::BuildJob::TryToBuild (this=0x4c0a790) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:111
#3  0x000000000077c5a6 in AIJH::BuildJob::ExecuteJob (this=0x4c0a790) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:48
#4  0x0000000000789e7c in AIJH::AIConstruction::ExecuteJobs (this=0x3aa94d0, limit=10)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:134
#5  0x0000000000764775 in AIJH::AIPlayerJH::ExecuteAIJob (this=0x128f1f0) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:819
#6  0x0000000000764010 in AIJH::AIPlayerJH::RunGF (this=0x128f1f0, gf=161990, gfisnwf=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:203
#7  0x0000000000575c61 in GameClient::NextGF (this=0x1241b90, wasNWF=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1321
#8  0x0000000000571ba5 in GameClient::ExecuteGameFrame (this=0x1241b90) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1259
#9  0x0000000000571805 in GameClient::Run (this=0x1241b90) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:182
#10 0x0000000000502076 in GameManager::Run (this=0xac1690) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/GameManager.cpp:113
#11 0x00000000004f1374 in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:382
#12 0x00000000004f10c0 in main (argc=<optimized out>, argv=<optimized out>) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:440
(gdb) continue
Assertion failure in "SimpleFindPosition" at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp#1.025: aii.GetBuildingQuality(curPt) == GetAINode(curPt).bq
```

replay: [2019-11-01_13-12-29.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/3797848/2019-11-01_13-12-29.rpl.zip)

### LINKED ISSUE #1128: Assertion failure in ConnectFlagToRoadSytem
```
Thread 1 "s25client" received signal SIGTRAP, Trace/breakpoint trap.
0x00005555558d8b80 in AIJH::AIConstruction::ConnectFlagToRoadSytem (
    this=this@entry=0x55555a4f5490, flag=flag@entry=0x55555823e2c0, route=..., 
    maxSearchRadius=maxSearchRadius@entry=14)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:331
331	/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00005555558d8b80 in AIJH::AIConstruction::ConnectFlagToRoadSytem (this=this@entry=0x55555a4f5490, flag=flag@entry=0x55555823e2c0, route=..., 
    maxSearchRadius=maxSearchRadius@entry=14) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:331
#1  0x00005555558bfdca in AIJH::BuildJob::BuildMainRoad (this=this@entry=0x555558b83f60)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:213
#2  0x00005555558c0070 in AIJH::BuildJob::ExecuteJob (this=0x555558b83f60) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/Jobs.cpp:50
#3  0x00005555558d82a2 in AIJH::AIConstruction::ExecuteJobs (this=0x55555a4f5490, limit=23)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp:134
#4  0x00005555558ab3ff in AIJH::AIPlayerJH::ExecuteAIJob (this=this@entry=0x555558108ec0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:819
#5  0x00005555558b6362 in AIJH::AIPlayerJH::RunGF (this=this@entry=0x555558108ec0, gf=196017, gfisnwf=gfisnwf@entry=true)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIPlayerJH.cpp:203
#6  0x000055555564f1ab in GameClient::NextGF (this=this@entry=0x5555562a7780, wasNWF=wasNWF@entry=true)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1321
#7  0x0000555555656571 in GameClient::ExecuteGameFrame (this=this@entry=0x5555562a7780)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:1259
#8  0x0000555555656cdd in GameClient::Run (this=0x5555562a7780) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:182
#9  0x00005555555cf89f in GameManager::Run (this=0x555555b2fe90)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp:72
#10 0x00005555555bed01 in (anonymous namespace)::RunProgram (options=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include/libutil/SingletonImp.hpp:72
#11 0x00005555555bf074 in main (argc=1, argv=0x7fffffffdc68) at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:440
(gdb) continue
Continuing.
Assertion failure in "ConnectFlagToRoadSytem" at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/ai/aijh/AIConstruction.cpp#331: aii.GetBuildingQuality(tmpPos) == aijh.GetAINode(tmpPos).bq
```
replay: [2019-11-01_17-26-45.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/3798760/2019-11-01_17-26-45.rpl.zip)

### PR DESCRIPTION
**Pull request by Flamefire**
Make the AI update its BQ map also on owner change

The players view on the BQ depends on the ownership of surrounding nodes hence use th ownership changed note and update BQ on that node and surrounding

Fixes #1127, fixes #1128 (same issue)

- [x] Includes #1269

### CODE REVIEW

File: libs/s25main/ai/aijh/AIConstruction.cpp [hunk 1]
```diff
@@ -212,7 +212,7 @@ std::vector<const noFlag*> AIConstruction::FindFlags(const MapPoint pt, unsigned
     // When the radius is at least half the size of the map then we may have duplicates that need to be removed
     if(radius >= std::min(aii.gwb.GetSize().x, aii.gwb.GetSize().y))
     {
-        helpers::makeUnique(flags);
+        helpers::makeUniqueStable(flags);
```
Comment (Flow86) [inline libs/s25main/ai/aijh/AIConstruction.cpp:215]: why not use https://en.cppreference.com/w/cpp/algorithm/unique ?

Comment (Flamefire) [reply libs/s25main/ai/aijh/AIConstruction.cpp:215]: The entries are sorted (by radius which is usually equal to the distance from `pt`) and `std::unique` requires a sorted container (see the new `makeUnique` which does the sort-unique-erase thing)

Nope we are using C++11 with some C++14 as someone wanted to keep the MSVC 2015 support.
