### PR TITLE
Plugin fixes

### LINKED ISSUE #1521: Nation specific catapult graphics broken
The addon "Race Specific Catapult Graphics" is currently broken. When fixing this, it should be renamed to "Nation Specific Catapult Graphics"

### PR DESCRIPTION
**Pull request by tehKaiN**
Fixes #1521 

obraz

Also brings back Military Aid to its full functionality (note the icon which indicates that enemy guardhouse can be attacked):

obraz

Submodule which needs to be merged prior to this one so that I can update submodule refs: https://github.com/Return-To-The-Roots/languages/pull/20

### CODE REVIEW

**Comment by tehKaiN** [comment]
I've made attack indicators optional, for ppl who may dislike them. Added relevant translations

obraz

obraz

File: libs/s25main/world/GameWorldView.cpp [hunk 1]
```diff
@@ -347,12 +347,18 @@ void GameWorldView::DrawNameProductivityOverlay(const TerrainRenderer& terrainRe
...
+            Position curPos = GetWorld().GetNodePos(pt) - offset + curOffset;
+            curPos.y -= 22;
+
             // Is object not belonging to local player?
             if(no->GetPlayer() != gwv.GetPlayerId())
+            {
+                auto* attackAidImage = LOADER.GetImageN("map_new", 20000);
+                if(GetWorld().GetGGS().getSelection(AddonId::MILITARY_AID) == 2)
+                    if(gwv.GetNumSoldiersForAttack(pt) > 0) // soldiers available for attack?
+                        attackAidImage->DrawFull(curPos - DrawPoint(0, attackAidImage->getHeight()));
```
Comment (Flamefire) [inline libs/s25main/world/GameWorldView.cpp:359]: Braces for multi-line code in branches:
```suggestion
                if(GetWorld().GetGGS().getSelection(AddonId::MILITARY_AID) == 2)
                {
                    if(gwv.GetNumSoldiersForAttack(pt) > 0) // soldiers available for attack?
                        attackAidImage->DrawFull(curPos - DrawPoint(0, attackAidImage->getHeight()));
                }
```

File: libs/s25main/world/GameWorldView.cpp [hunk 2]
```diff
@@ -484,7 +490,7 @@ void GameWorldView::DrawConstructionAid(const MapPoint& pt, const DrawPoint& cur
         // Draw building quality icon
         bm->DrawFull(curPos);
         // Show ability to construct military buildings
-        if(GetWorld().GetGGS().isEnabled(AddonId::MILITARY_AID))
+        if(GetWorld().GetGGS().getSelection(AddonId::MILITARY_AID) > 0)
```
Comment (Flamefire) [inline libs/s25main/world/GameWorldView.cpp:493]: Why this change? `isEnabled` already does exactly this.

**Review by Flamefire — CHANGES_REQUESTED** [review]
Thanks a lot! Only 2 minor issues

And please use the imperative as commit messages. E.g. "Fix loading of plugin graphics". If you are comfortable with git amend and force push you can change the existing commits (message and include style fixes in the commit that added/changed the code) otherwise just keep it in mind for the future.

File: libs/s25main/world/GameWorldView.cpp (hunk 2 above)
Comment (tehKaiN) [reply libs/s25main/world/GameWorldView.cpp:493]: Because I've changed setting to list instead of bool, so that there are now 3 states of it: "off", "only construction aid", and "construction and attack aid". I assumed that `isEnabled` is only part of bool-based plugins, perhaps I was wrong about it. I'll check that out tomorrow

**Comment by tehKaiN** [comment]
Thanks for feedback! I'll rewrite my git history tomorrow so that commit messages are more uniform with your guidelines.

File: libs/s25main/world/GameWorldView.cpp (hunk 2 above)
Comment (Flamefire) [reply libs/s25main/world/GameWorldView.cpp:495]: `isEnabled` is a shortcut for `isNotDefault`, i.e. the default for an addon should be the original S2 behavior, i.e. "disabled"
Hence the name.

Comment (tehKaiN) [reply libs/s25main/world/GameWorldView.cpp]: fixed!

File: libs/s25main/world/GameWorldView.cpp [hunk 3]
```diff
@@ -347,12 +347,18 @@ void GameWorldView::DrawNameProductivityOverlay(const TerrainRenderer& terrainRe
...
 
+            Position curPos = GetWorld().GetNodePos(pt) - offset + curOffset;
+            curPos.y -= 22;
+
             // Is object not belonging to local player?
             if(no->GetPlayer() != gwv.GetPlayerId())
+            {
+                auto* attackAidImage = LOADER.GetImageN("map_new", 20000);
+                if(GetWorld().GetGGS().getSelection(AddonId::MILITARY_AID) == 2)
+                    if(gwv.GetNumSoldiersForAttack(pt) > 0) // soldiers available for attack?
```
Comment (Flow86) [inline libs/s25main/world/GameWorldView.cpp:358]: still missing the braces here.

Comment (tehKaiN) [reply libs/s25main/world/GameWorldView.cpp]: oops! I've just merged those into single `if` instead.

File: libs/s25main/world/GameWorldView.cpp [hunk 4]
```diff
@@ -347,12 +347,17 @@ void GameWorldView::DrawNameProductivityOverlay(const TerrainRenderer& terrainRe
             if(!no)
                 continue;
 
+            Position curPos = GetWorld().GetNodePos(pt) - offset + curOffset;
+            curPos.y -= 22;
+
             // Is object not belonging to local player?
             if(no->GetPlayer() != gwv.GetPlayerId())
+            {
+                auto* attackAidImage = LOADER.GetImageN("map_new", 20000);
```
Comment (Flamefire) [inline libs/s25main/world/GameWorldView.cpp:356]: Try to avoid doing needless work. E.g. getting the image when you rarely need it (the condition below is mostly false)
So put this into the block guarded by the `if`

Just for context what happens in `LOADER.GetImageN("map_new", 20000);`

- Look up the Singleton object
- Construct a string-like
- Search a map
- Access a large vector (cache miss likely)
- Cast the result

**Review by Flamefire — CHANGES_REQUESTED** [review]
One last remark concerning performance, besides that it looks good! 👍

File: libs/s25main/world/GameWorldView.cpp (hunk 4 above)
Comment (tehKaiN) [reply libs/s25main/world/GameWorldView.cpp:356]: Yeah, I thought about it, but then I saw that current code for military aid for construction is doing basically the same:

```cpp
void GameWorldView::DrawConstructionAid(const MapPoint& pt, const DrawPoint& curPos)
{
    BuildingQuality bq = gwv.GetBQ(pt);
    if(bq != BuildingQuality::Nothing)
    {
        constexpr auto bqImgs = getBqImgs();
        auto* bm = LOADER.GetMapTexture(bqImgs[bq]);
        // Draw building quality icon
        bm->DrawFull(curPos);
        // Show ability to construct military buildings
        if(GetWorld().GetGGS().isEnabled(AddonId::MILITARY_AID))
        {
            if(!GetWorld().IsMilitaryBuildingNearNode(pt, gwv.GetPlayerId())
               && (bq == BuildingQuality::Hut || bq == BuildingQuality::House || bq == BuildingQuality::Castle
                   || bq == BuildingQuality::Harbor))
                LOADER.GetImageN("map_new", 20000)->DrawFull(curPos - DrawPoint(-1, bm->GetSize().y + 5));
        }
    }
}
```

so I thought that we're good here and by the power of constexpr, compiler optimization and other black magic we're good with this approach. Ideally, this icon should be loaded once for whole GameWorldView, provided that plugin is enabled, and be used straight from dedicated object field.

**Comment by tehKaiN** [comment]
I've moved LOADER thingy inside `if` as you requested. Perhaps I should do additional work by moving that call into constructor and storing result in the field as I mentioned earlier?

File: libs/s25main/world/GameWorldView.cpp (hunk 4 above)
Comment (Flamefire) [reply libs/s25main/world/GameWorldView.cpp]: Sorry? In that code every image that is loaded is also used.

File: libs/s25main/world/GameWorldView.cpp [hunk 5]
```diff
@@ -347,12 +347,18 @@ void GameWorldView::DrawNameProductivityOverlay(const TerrainRenderer& terrainRe
...
 
+            Position curPos = GetWorld().GetNodePos(pt) - offset + curOffset;
+            curPos.y -= 22;
+
             // Is object not belonging to local player?
             if(no->GetPlayer() != gwv.GetPlayerId())
+            {
+                if(GetWorld().GetGGS().getSelection(AddonId::MILITARY_AID) == 2 && gwv.GetNumSoldiersForAttack(pt) > 0)
+                {
+                    LOADER.GetImageN("map_new", 20000)->DrawFull(curPos - DrawPoint(0, attackAidImage->getHeight()));
```
Comment (Flamefire) [inline libs/s25main/world/GameWorldView.cpp:358]:
```suggestion
                    auto* attackAidImage =  LOADER.GetImageN("map_new", 20000);
                    attackAidImage->DrawFull(curPos - DrawPoint(0, attackAidImage->getHeight()));
```

**Comment by Flamefire** [comment]
> Perhaps I should do additional work by moving that call into constructor and storing result in the field as I mentioned earlier?

Yes that might make sense. But then we might want to do that for every texture used which can be an own PR as it will likely be large

File: libs/s25main/world/GameWorldView.cpp (hunk 4 above)
Comment (tehKaiN) [reply libs/s25main/world/GameWorldView.cpp]: yeah but it is loaded very often nonetheless - for each construction icon which qualify as spot for military building as I understand it.

**Comment by Flamefire** [comment]
Seems there was an extra space in the suggestion. Sorry for that, could you fix that? Rest looks good

**Comment by tehKaiN** [comment]
fixed!

**Comment by tehKaiN** [comment]
so, can we merge this, or is there something else which I have to fix? :)

**Review by Flamefire — APPROVED** [review]
