### PR TITLE
Fix crash on map param

### LINKED ISSUE #1218: crash when s25client help
So I know the command should be `s25client --help`, but if you write `s25client help` without the **--** you get a crash.

Version info:
`>s25client.exe --version
Return To The Roots v20200430-1960d86e3e4c4f9fb4c8c3976d9eab4bc8e5b837
Compiled with GNU C++ version 7.3-win32 20180506 for Win32 64 Bit`

### PR DESCRIPTION
**Pull request by Flamefire**
Fixes #1218 

Larger refactoring to get loading of data into a reusable class. Also avoid the use of the Singletons (want to get rid of them eventually)

Not fully satisfied with the solution as there is still duplicated code. More maybe in future PRs

### CODE REVIEW

File: libs/s25main/MusicPlayer.cpp [hunk 1]
```diff
@@ -15,184 +15,31 @@
...
-#include "ingameWindows/iwMusicPlayer.h"
 #include "ogl/MusicItem.h"
 #include "libsiedler2/Archiv.h"
 #include "libsiedler2/ArchivItem.h"
 #include "libsiedler2/ErrorCodes.h"
 #include "libsiedler2/prototypen.h"
 #include "s25util/Log.h"
 #include "s25util/StringConversion.h"
+
+/*
```
Comment (Flow86) [inline libs/s25main/MusicPlayer.cpp:29]: dead code

Comment (Flamefire) [reply libs/s25main/MusicPlayer.cpp]: Thanks, fixed
