### PR TITLE
Fix crash when asking for defenders of harbor with waiting attackers

### LINKED ISSUE #1912: Random crashes since 09-04-2026 release (?on multiplayer with harbours?)
With the version of 20260409 I'm experiencing random crashes on levels that used to never have problems. All the levels have harbours that is the only common theme (although I've not tested multiplayer levels without harbours yet). I tested an older version (16-03) with the same map that crashed multiplayer ran stable on singleplayer (friends were not around to test multiplayer as well). 

Sometimes Im able to submit the debug logs, not always, sometimes in I see a message similar to 'pure virtual method called' sometimes nothing at all. In the windows event log I do so some things that (according to chatgpt) are caused by memory access being denied

building initially works fine, when attacks are beginning it crashed randomly, not the first attack maybe, but at some point every minute or so, restarting from savegame gives maybe another minute of playing time before crashing again. I've not found a pattern or exact moment though... 

I'm suspecting it has to do with this PR https://github.com/Return-To-The-Roots/s25client/pull/1910 

The Exception code: 0xc0000005 is apperearently a memory access violation. 

Log from windows event: 
`Faulting application name: s25client.exe,
 version: 0.0.0.0, 
time stamp: 0x00000000 Faulting module name: unknown, 
version: 0.0.0.0, time stamp: 0x00000000 
Exception code: 0xc0000005 
Fault offset: 0x000000010057f2cb 
Faulting process id: 0x5708
 Faulting application start time: 0x1DCCEA0B1D2DB67 
Faulting application path: F:\s2g\s25client.exe 
Faulting module path: unknown Report Id: 6766b7b3-65df-4331-9a83-003c43276629 Faulting package full name: Faulting package-relative application ID:`

WER report from windows logging (clipped it a little)
`Version=1 EventType=BEX64 EventTime=134209282140889462 ReportType=2 Consent=1 UploadTime=134209282143136510 ReportStatus=268435456 ReportIdentifier=93e0da65-cd17-46ac-8527-531d7d10bf1d IntegratorReportIdentifier=6766b7b3-65df-4331-9a83-003c43276629 Wow64Host=34404 NsAppName=s25client.exe AppSessionGuid=00005708-0001-004a-67db-d2b1a0cedc01 TargetAppId=W:0006214ba7990e7846a6a6a6b7ab6a987beb0000ffff!00005f355db6ac25820c5626791dcde9d05a0f958e56!s25client.exe TargetAppVer=1970//01//01:00:00:00!7e5e64!s25client.exe BootId=4294967295 TargetAsId=7036 UserImpactVector=808465200 IsFatal=1 EtwNonCollectReason=1 Response.BucketId=cd49c2f11f0195072993e0f44ecd91aa Response.BucketTable=5 Response.LegacyBucketId=1843064012423401898 Response.type=4 Sig[0].Name=Application Name Sig[0].Value=s25client.exe Sig[1].Name=Application Version Sig[1].Value=0.0.0.0 Sig[2].Name=Application Timestamp Sig[2].Value=00000000 Sig[3].Name=Fault Module Name Sig[3].Value=StackHash_83c4 Sig[4].Name=Fault Module Version Sig[4].Value=0.0.0.0 Sig[5].Name=Fault Module Timestamp Sig[5].Value=00000000 Sig[6].Name=Exception Offset Sig[6].Value=PCH_29_FROM_unknown+0x0000000000000000 Sig[7].Name=Exception Code Sig[7].Value=c0000005 Sig[8].Name=Exception Data Sig[8].Value=0000000000000008 DynamicSig[1].Name=OS Version DynamicSig[1].Value=10.0.26200.2.0.0.768.101 DynamicSig[2].Name=Locale ID DynamicSig[2].Value=2057 DynamicSig[22].Name=Additional Information 1 DynamicSig[22].Value=83c4 DynamicSig[23].Name=Additional Information 2 DynamicSig[23].Value=83c434029c1ebe1f4a6fe53c028091ca DynamicSig[24].Name=Additional Information 3 DynamicSig[24].Value=fcf6 DynamicSig[25].Name=Additional Information 4 DynamicSig[25].Value=fcf6d36d741b11a1276a6712f44bd14b UI[2]=F:\s2g\s25client.exe LoadedModule[0]=F:\s2g\s25client.exe LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll LoadedModule[4]=C:\WINDOWS\System32\ADVAPI32.dll LoadedModule[5]=F:\s2g\lua52.dll LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll LoadedModule[7]=C:\WINDOWS\System32\sechost.dll LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll LoadedModule[9]=C:\WINDOWS\System32\ole32.dll LoadedModule[10]=C:\WINDOWS\System32\msvcp_win.dll LoadedModule[11]=C:\WINDOWS\System32\ucrtbase.dll LoadedModule[12]=C:\WINDOWS\System32\GDI32.dll LoadedModule[13]=C:\WINDOWS\System32\win32u.dll LoadedModule[14]=C:\WINDOWS\System32\gdi32full.dll LoadedModule[15]=C:\WINDOWS\System32\USER32.dll LoadedModule[16]=C:\WINDOWS\System32\combase.dll LoadedModule[17]=C:\WINDOWS\System32\SHELL32.dll LoadedModule[18]=C:\WINDOWS\System32\wintypes.dll LoadedModule[19]=F:\s2g\libwinpthread-1.dll LoadedModule[20]=C:\WINDOWS\System32\WS2_32.dll LoadedModule[21]=C:\WINDOWS\SYSTEM32\Secur32.dll LoadedModule[22]=F:\s2g\libgcc_s_seh-1.dll LoadedModule[23]=F:\s2g\libstdc++-6.dll LoadedModule[24]=F:\s2g\libminiupnpc.dll LoadedModule[25]=F:\s2g\libiconv-2.dll LoadedModule[26]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL LoadedModule[27]=C:\WINDOWS\SYSTEM32\SSPICLI.DLL LoadedModule[28]=C:\WINDOWS\System32\IMM32.DLL LoadedModule[29]=C:\WINDOWS\System32\shcore.dll LoadedModule[30]=C:\WINDOWS\System32\windows.storage.dll LoadedModule[31]=C:\WINDOWS\System32\shlwapi.dll LoadedModule[32]=C:\WINDOWS\SYSTEM32\profapi.dll LoadedModule[33]=F:\s2g\driver\video\libvideoSDL2.dll LoadedModule[34]=F:\s2g\SDL2.dll LoadedModule[35]=C:\WINDOWS\System32\OLEAUT32.dll LoadedModule[36]=C:\WINDOWS\System32\SETUPAPI.dll LoadedModule[37]=C:\WINDOWS\SYSTEM32\VERSION.dll LoadedModule[38]=C:\WINDOWS\SYSTEM32\WINMM.dll LoadedModule[39]=C:\WINDOWS\system32\uxtheme.dll LoadedModule[40]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.26100.8115_none_3e075c82e3354f9c\comctl32.dll LoadedModule[41]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll LoadedModule[42]=C:\WINDOWS\SYSTEM32\mscms.dll LoadedModule[43]=C:\WINDOWS\SYSTEM32\icm32.dll LoadedModule[44]=C:\WINDOWS\SYSTEM32\OPENGL32.DLL LoadedModule[45]=C:\WINDOWS\SYSTEM32\GLU32.dll LoadedModule[46]=C:\WINDOWS\SYSTEM32\dxcore.dll LoadedModule[47]=C:\WINDOWS\System32\MSCTF.dll LoadedModule[48]=C:\WINDOWS\SYSTEM32\windows.staterepositorycore.dll LoadedModule[49]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_e980fd2c7c4fce8e\nvoglv64.dll LoadedModule[50]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll LoadedModule[51]=C:\WINDOWS\System32\CRYPT32.dll LoadedModule[52]=C:\WINDOWS\SYSTEM32\msasn1.dll LoadedModule[53]=C:\WINDOWS\SYSTEM32\cryptnet.dll LoadedModule[54]=C:\WINDOWS\SYSTEM32\cryptbase.dll LoadedModule[55]=C:\WINDOWS\SYSTEM32\wldp.dll LoadedModule[56]=C:\WINDOWS\SYSTEM32\drvstore.dll LoadedModule[57]=C:\WINDOWS\SYSTEM32\devobj.dll LoadedModule[58]=C:\WINDOWS\SYSTEM32\cfgmgr32.dll LoadedModule[59]=C:\WINDOWS\System32\WINTRUST.dll LoadedModule[60]=C:\WINDOWS\SYSTEM32\ntmarta.dll LoadedModule[61]=C:\WINDOWS\System32\imagehlp.dll LoadedModule[62]=C:\WINDOWS\System32\CRYPTSP.dll LoadedModule[63]=C:\WINDOWS\system32\rsaenh.dll LoadedModule[64]=C:\WINDOWS\System32\bcryptPrimitives.dll LoadedModule[65]=C:\WINDOWS\System32\bcrypt.dll LoadedModule[66]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_e980fd2c7c4fce8e\nvgpucomp64.dll LoadedModule[67]=C:\WINDOWS\system32\nvspcap64.dll LoadedModule[68]=C:\WINDOWS\SYSTEM32\dwmapi.dll LoadedModule[69]=C:\WINDOWS\SYSTEM32\powrprof.dll LoadedModule[70]=C:\WINDOWS\SYSTEM32\UMPDC.dll LoadedModule[71]=C:\WINDOWS\SYSTEM32\WINSTA.dll LoadedModule[72]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll LoadedModule[73]=C:\WINDOWS\System32\clbcatq.dll LoadedModule[74]=C:\WINDOWS\SYSTEM32\textinputframework.dll LoadedModule[75]=C:\WINDOWS\SYSTEM32\CoreMessaging.dll LoadedModule[76]=C:\WINDOWS\SYSTEM32\CoreUIComponents.dll LoadedModule[77]=F:\s2g\driver\audio\libaudioSDL.dll LoadedModule[78]=F:\s2g\SDL2_mixer.dll LoadedModule[79]=C:\WINDOWS\System32\MMDevApi.dll LoadedModule[80]=C:\WINDOWS\SYSTEM32\avrt.dll LoadedModule[81]=C:\WINDOWS\SYSTEM32\AUDIOSES.DLL LoadedModule[82]=C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll LoadedModule[83]=C:\WINDOWS\system32\mswsock.dll State[0].Key=Transport.DoneStage1 State[0].Value=1 OsInfo[0].Key=vermaj OsInfo[0].Value=10 OsInfo[1].Key=vermin OsInfo[1].Value=0 OsInfo[2].Key=verbld OsInfo[2].Value=26200 OsInfo[3].Key=ubr OsInfo[3].Value=8246 OsInfo[4].Key=versp OsInfo[4].Value=0 OsInfo[5].Key=arch OsInfo[5].Value=9 OsInfo[6].Key=lcid OsInfo[6].Value=2057 OsInfo[7].Key=geoid OsInfo[7].Value=176 OsInfo[8].Key=sku OsInfo[8].Value=101 OsInfo[9].Key=domain OsInfo[9].Value=0 OsInfo[10].Key=prodsuite OsInfo[10].Value=768 OsInfo[11].Key=ntprodtype OsInfo[11].Value=1 OsInfo[12].Key=platid OsInfo[12].Value=10 OsInfo[13].Key=sr OsInfo[13].Value=0 OsInfo[14].Key=tmsi OsInfo[14].Value=223679176 OsInfo[15].Key=osinsty OsInfo[15].Value=3 OsInfo[16].Key=iever OsInfo[16].Value=11.1882.26100.0-11.0.1000 OsInfo[17].Key=portos OsInfo[17].Value=0 OsInfo[18].Key=ram OsInfo[18].Value=65309 OsInfo[19].Key=svolsz OsInfo[19].Value=220 OsInfo[20].Key=wimbt OsInfo[20].Value=0 OsInfo[21].Key=blddt OsInfo[21].Value=240331 OsInfo[22].Key=bldtm OsInfo[22].Value=1435 OsInfo[23].Key=bldbrch OsInfo[23].Value=ge_release OsInfo[24].Key=bldchk OsInfo[24].Value=0 OsInfo[25].Key=wpvermaj OsInfo[25].Value=0 OsInfo[26].Key=wpvermin OsInfo[26].Value=0 OsInfo[27].Key=wpbuildmaj OsInfo[27].Value=0 OsInfo[28].Key=wpbuildmin OsInfo[28].Value=0 OsInfo[29].Key=osver OsInfo[29].Value=10.0.26100.8246.amd64fre.ge_release.240331-1435 OsInfo[30].Key=buildflightid OsInfo[30].Value=AD27E52B-9E18-408A-9DF2-8688E5273FBF.1 OsInfo[31].Key=edition OsInfo[31].Value=Core OsInfo[32].Key=ring OsInfo[32].Value=Retail OsInfo[33].Key=flightbranch OsInfo[34].Key=expid`

### PR DESCRIPTION
**Pull request by Flamefire**
What happened:
- Sea attack starts
- Attacker arrives in start harbor and waits for ship
- target is destroyed, attacker prepares to leave to go back home
- harbor is attacked
- "active" soldiers that want to leave are stopped, including this attacker
- code wrongly considers this as belonging to this building

This was indeed introduced by #1910
Prior to that such a soldier would be ignored here.

The result is:
- Harbor is attacked
- Soldier gets notified its goal has already been destroyed
- He goes home
- Comes out and ignores the ongoing fight, YOLO

The idea is to potentially use those for defense.
However e.g. harbors might contain soldiers that belong to another
building and are about to leave.

Don't consider those as this complicates the logic too much and just revert to this behavior.

It fixes the crash which is prior to that caught by an assertion: The soldier is not in `troop_on_mission`.
Fixes #1912

Also fix an assertion failure that detected a mismatch in expected armors: There could be more armored soldiers than soldiers (logic is we have n of m soldiers with armor)
This is detected by continuing the provided savegame.

To avoid similar issues I deduplicated code handling the warehouse inventory: Boat-carrier, soldier and others have to be handled consistently

### CODE REVIEW

File: libs/s25main/buildings/nobBaseMilitary.cpp [hunk 1]
```diff
@@ -236,6 +235,12 @@ bool nobBaseMilitary::CallDefender(nofAttacker& attacker)
 
             soldier->InformTargetsAboutCancelling();
             AddActiveSoldier(std::move(soldier));
+        } else
+        {
+            // If a leaving active soldier is not on a mission he doesn't belong to this building.
+            // E.g. soldiers in harbors could be about to go home.
+            RTTR_Assert(!sldPtr || sldPtr->GetHomeBld() != this);
```
Comment (Flow86) [inline libs/s25main/buildings/nobBaseMilitary.cpp:242]: this assert doesnt make sense to me in combination with the comment?

File: libs/s25main/figures/nofActiveSoldier.cpp [hunk 2]
```diff
@@ -43,11 +43,11 @@ void nofActiveSoldier::GoalReached()
 {
     // We reached the military building
     // Add myself to the building
-    if(!building)
+    if(!homeBld)
```
Comment (Flow86) [inline libs/s25main/figures/nofActiveSoldier.cpp:46]: if we do pascal case here, lets write it out, `homeBuilding`

File: libs/s25main/figures/nofSoldier.cpp [hunk 3]
```diff
@@ -12,15 +12,15 @@
...
+    : noFigure(SOLDIER_JOBS[rank], pos, player, goal), homeBld(home), hitpoints(HITPOINTS[rank])
 {
     hasArmor_ = armor;
     RTTR_Assert(IsSoldier());
 }
 
 nofSoldier::nofSoldier(const MapPoint pos, const unsigned char player, nobBaseMilitary& home, const unsigned char rank,
                        bool armor)
-    : noFigure(SOLDIER_JOBS[rank], pos, player), building(&home), hitpoints(HITPOINTS[rank])
+    : noFigure(SOLDIER_JOBS[rank], pos, player), homeBld(&home), hitpoints(HITPOINTS[rank])
```
Comment (Flow86) [inline libs/s25main/figures/nofSoldier.cpp:23]: can't we not use constructor chaining in the mean time?

File: libs/s25main/figures/nofSoldier.h [hunk 4]
```diff
@@ -39,10 +38,10 @@ class nofSoldier : public noFigure
     }
     void Serialize(SerializedGameData& sgd) const override;
 
-    /// Liefert Rang des Soldaten
     unsigned char GetRank() const;
     unsigned char GetHitpoints() const;
-    bool HasNoHome() const { return building == nullptr; }
+    bool HasNoHome() const { return homeBld == nullptr; }
```
Comment (Flow86) [inline libs/s25main/figures/nofSoldier.h]: I would swap it around `HasHome`

File: libs/s25main/figures/nofActiveSoldier.cpp (hunk 2 above)
Comment (Flamefire) [reply libs/s25main/figures/nofActiveSoldier.cpp:46]: We used "bld" in many other places:
GetBld, numBlds, OldBldIt, milBld, sortedMilitaryBlds, goalBld

So it is most consistent to do that here too

File: libs/s25main/figures/nofSoldier.cpp (hunk 3 above)
Comment (Flamefire) [reply libs/s25main/figures/nofSoldier.cpp:23]: What do you mean? Calling the base class constructor doesn't really has alternatives, does it?

File: libs/s25main/buildings/nobBaseMilitary.cpp (hunk 1 above)
Comment (Flamefire) [reply libs/s25main/buildings/nobBaseMilitary.cpp:242]: The assert reads: "Either it is not a leaving active soldier or he doesn't belong here" given we know he is not on a mission

File: libs/s25main/figures/nofSoldier.h (hunk 4 above)
Comment (Flamefire) [reply libs/s25main/figures/nofSoldier.h]: Actually it doesn't make much sense anymore given the newly introduced `GetHome`. So removed that and the related `HasNoGoal`

As for the name: I guess we usually just needed the negated version: `if(hasNoHome) abortFight`

File: libs/s25main/buildings/nobBaseMilitary.cpp (hunk 1 above)
Comment (Flow86) [reply libs/s25main/buildings/nobBaseMilitary.cpp:242]: ah so otherwise it wouldnt be an active soldier, right? ok, I understand now

File: libs/s25main/figures/nofSoldier.cpp (hunk 3 above)
Comment (Flow86) [reply libs/s25main/figures/nofSoldier.cpp:23]: you could call

```suggestion
    : nofSoldier(pos, player, nullptr, &home, rank, armor)
{}
```
can't we? or is the `goal` not to be allowed to be a `nullptr`? because thats the only difference between the two constructors

Comment (Flamefire) [reply libs/s25main/figures/nofSoldier.cpp:23]: Isn't that constructor chaining? Forwarding the ctor to another of the same class?

Anyway: The 2 noFigure constructors are different. One sets the state to `fs(FigureState::GotToGoal)` the other to `FigureState::Job`

Confusingly the former accepts no goal which seems wrong but not sure if it isn't used somewhere.

So at this point I really don't want to touch this, especially not here where nothing but a name is changed

Comment (Flow86) [reply libs/s25main/figures/nofSoldier.cpp:23]: okay the offical term is "constructor delegation" it seems, but ok keep it that way

https://www.geeksforgeeks.org/cpp/constructor-delegation-c/

**Review by Flow86 — APPROVED** [review]
