### PR TITLE
Fix geologist loading

### LINKED ISSUE #1332: failed to load savegame with latest git (follow up issue)
I just compiled the latest git version from b14a405b56bb55b805c20952c964c8cf85bde145, and it crashes when I try to load a saved game:

client state changed to stop
Connection to 127.0.0.1:3.665
Successfully connected to localhost:3.665
SERVER: Using gameframe length of 50ms
SERVER: Using networkframe length of 1 GFs (50ms)
s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp:105: bool Serializer::PopBool(): Zusicherung »value == 0 || value == 1« nicht erfüllt.
Abgebrochen

here is a backtrace when compiled with clang-10; also please note that the backtrace escalates into libc, for which I had to set up debug symbols first and can't recall I ever had to for this project: 

```

Successfully connected to localhost:3.665
SERVER: Using gameframe length of 50ms
SERVER: Using networkframe length of 1 GFs (50ms)
s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp:105: bool Serializer::PopBool(): Zusicherung »value == 0 || value == 1« nicht erfüllt.

Thread 1 "s25client" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7d54536 in __GI_abort () at abort.c:79
#2  0x00007ffff7d5441f in __assert_fail_base (fmt=0x7ffff51be583 "%s%s%s:%u: %s%sZusicherung »%s« nicht erfüllt.\n%n", assertion=0x7bc536 "value == 0 || value == 1", 
    file=0x7bc54f "/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp", line=105, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff7d63462 in __GI___assert_fail (assertion=0x7bc536 "value == 0 || value == 1", 
    file=0x7bc54f "/var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp", line=105, 
    function=0x7bc5c1 "bool Serializer::PopBool()") at assert.c:101
#4  0x000000000075e0f0 in Serializer::PopBool (this=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/external/libutil/libs/common/src/Serializer.cpp:105
#5  0x00000000006156b8 in nofGeologist::nofGeologist (this=0x31fab00, sgd=..., obj_id=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/figures/nofGeologist.cpp:75
#6  0x0000000000580a63 in SerializedGameData::Create_GameObject (this=0x3237470, got=<optimized out>, obj_id=4492)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:145
#7  0x00000000005826e4 in SerializedGameData::PopObject_ (this=0x3237470, got=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:454
#8  0x00000000006247a6 in SerializedGameData::PopObject<noBase> (this=0x2, got=50608)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.h:131
#9  0x000000000062481a in SerializedGameData::PopObjectContainer<std::__cxx11::list<noBase*, std::allocator<noBase*> > > (this=0x3237470, gos=..., got=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.h:237
#10 0x00000000006242d1 in MapNode::Deserialize (this=0x58e6020, sgd=..., numPlayers=3, desc=..., landscapeTerrains=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/gameTypes/MapNode.cpp:92
#11 0x0000000000531827 in MapSerializer::Deserialize (world=..., numPlayers=3, sgd=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/MapSerializer.cpp:114
#12 0x0000000000509a5f in GameWorld::Deserialize (this=0x234de48, game=..., localgameState=..., sgd=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/world/GameWorld.cpp:97
#13 0x0000000000581a8d in SerializedGameData::ReadSnapshot (this=0x3237470, game=..., localGameState=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/SerializedGameData.cpp:275
#14 0x00000000004caad1 in GameClient::StartGame (this=0xedde30, random_init=0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:302
#15 0x00000000004cbf75 in GameClient::OnGameMessage (this=0xedde30, msg=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:747
#16 0x00000000004dd3c6 in GameMessage_Server_Start::Run (this=0x5402900, callback=0xedde30)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameMessages.h:222
#17 0x00000000004dc49b in GameMessage::run (this=0x5402900, callback=<optimized out>, senderPlayerID=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameMessage.cpp:26
#18 0x00000000004f2744 in NetworkPlayer::executeMsgs (this=0xeddf00, msgHandler=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/NetworkPlayer.cpp:57
#19 0x00000000004c9fb9 in GameClient::Run (this=0xedde30) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/network/GameClient.cpp:188
#20 0x0000000000446aa2 in GameManager::Run (this=0x7fffffffd6d8) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25main/GameManager.cpp:118
#21 0x0000000000435118 in (anonymous namespace)::RunProgram (options=...) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:476
#22 0x0000000000434ac1 in main (argc=<optimized out>, argv=<optimized out>) at /var/tmp/portage/games-strategy/s25rttr-9999-r5/work/s25rttr-9999/libs/s25client/s25client.cpp:553

```

### PR DESCRIPTION
**Pull request by Flamefire**
We didn't serialize fish and water before where not serializing water was an actual bug (it is used with exhaustible water addon)
Serializing fish is not required now but makes the code easier.

Fixes #1332

### CODE REVIEW

**Comment by Flow86** [comment]
does this fix #1332 ?

File: libs/s25main/figures/nofGeologist.cpp [hunk 1]
```diff
@@ -71,8 +72,18 @@ nofGeologist::nofGeologist(SerializedGameData& sgd, const unsigned obj_id)
...
+    if(sgd.GetGameDataVersion() < 6)
+    {
+        for(const auto res : helpers::enumRange<ResourceType>())
+        {
+            if(res != ResourceType::Fish && res != ResourceType::Water)
+                resAlreadyFound[res] = sgd.PopBool();
+        }
+    } else
+    {
+        for(bool& found : resAlreadyFound)
```
Comment (Flow86) [inline libs/s25main/figures/nofGeologist.cpp:84]: can this work at all? isnt "resAlreadyFound" empty on load?

Comment (Flow86) [reply libs/s25main/figures/nofGeologist.cpp:84]: ah forget it, its always filled. ok :-)

**Comment by stefson** [comment]
this is fixed now, thanks :)

File: libs/s25main/figures/nofGeologist.cpp (hunk 1 above)
Comment (Flamefire) [reply libs/s25main/figures/nofGeologist.cpp:84]: It is a fixed size array ;)
We could however provide serialization function pairs for those to avoid such loops.
