### PR TITLE
Fix loading of overrides

### LINKED ISSUE #1112: Overriding graphics seems no longer to function
After years I continued working on the babyolian scout. So I created a 8 graphic animation for left-top and wanted to test them. So I tried to replace the original roman graphics by creating a JOBS.BOB folder here `s25rttr_20190820\RTTR\LSTS\GAME\JOBS.BOB` Sadly those graphics seem not to replace the original graphics at all. So tried to unpack the following file: `s25rttr_20190820\RTTR\LSTS\GAME\Babylonier\JOBS.BOB.LST` and repalced the graphics in that folder.

There still seems to be no effect at all which is strange in two ways as I expected the second file to be in use.
The game says it loads the graphics but seems to not overwrite existing files anymore (or loads the jobs file after).

Has there been a change I missed on how to replace graphics or am I doing something wrong?

### PR DESCRIPTION
**Pull request by Flamefire**
This fixes #1112

The main points are:
- resources (images, sounds, ...) are identified by a `ResourceId`
- That is a simple name, all lowercase so extensions and casing do not matter
- Folders should still have an extension (usually either .lst or .bob) to be considered for loading when scanning the folder, but not duplicate extensions
- files may have duplicate extensions. This is only useful for bob files, like foo.bob.lst where the .lst means to load it as lst format, then handle it as a bob resource to add to resource foo
- bob resources have a single archive as their first entry containing the graphics. For folders or files not named `*.bob` this is done by the loader to be compatible with `*.bob` files

Some related changes are included:
- Better naming for Loader::Load methods
- Usage of boost::filesystem::path where a real path is wanted
- introduce toLower function as `std::tolower` is potentially dangerous to use directly (see cppreference)
- fix a long standing TODO related to `nation_gfx` which should only contain nations actually loaded. This improves loading times probably a lot as the loop at https://github.com/Return-To-The-Roots/s25client/compare/master...Flamefire:bob_loading?expand=1#diff-f26a4af6ca06758a8f91142fea989e52R495 can be fully skipped for those not trying to load hundreds of non-existing images

All of those came up in the refactoring to understand the code and implement the feature. IMO it is much cleaner now.

### CODE REVIEW

File: libs/s25main/Loader.cpp [hunk 1]
```diff
@@ -280,7 +288,7 @@ bool Loader::LoadSounds()
 
 bool Loader::LoadFonts()
 {
-    if(!LoadFile(config_.ExpandPath("<RTTR_RTTR>/LSTS/fonts.LST"), GetPaletteN("pal5")))
+    if(!Load(config_.ExpandPath("<RTTR_RTTR>/LSTS/fonts.LST"), GetPaletteN("pal5")))
```
Comment (Flow86) [inline libs/s25main/Loader.cpp:291]: should the path here possibly also added to the FILE_PATHS or at least as a global constant in the same file as the rest of the paths, that way we have them in one place.

File: libs/s25main/Loader.cpp [hunk 2]
```diff
@@ -357,47 +365,46 @@ void Loader::LoadDummyGUIFiles()
...
  *
- *  @return @p true bei Erfolg, @p false bei Fehler.
+ *  @return @p true on success
  */
-bool Loader::LoadFilesAtGame(const std::string& mapGfxPath, bool isWinterGFX, const std::vector<bool>& nations)
+bool Loader::LoadFilesAtGame(const std::string& mapGfxPath, bool isWinterGFX, const std::vector<Nation>& nations)
 {
-    if(NAT_BABYLONIANS < nations.size() && nations[NAT_BABYLONIANS])
+    if(helpers::contains(nations, NAT_BABYLONIANS))
         AddOverrideFolder("<RTTR_RTTR>/LSTS/GAME/Babylonier", false);
```
Comment (Flow86) [inline libs/s25main/Loader.cpp:379]: same for here

File: libs/s25main/Loader.cpp [hunk 3]
```diff
@@ -930,140 +949,156 @@ bool Loader::MergeArchives(libsiedler2::Archiv& targetArchiv, libsiedler2::Archi
...
-    filesAndFolders = ListDir(path, "idx", true, &filesAndFolders);
-    filesAndFolders = ListDir(path, "bmp", true, &filesAndFolders);
-    filesAndFolders = ListDir(path, "txt", true, &filesAndFolders);
-    filesAndFolders = ListDir(path, "ger", true, &filesAndFolders);
-    filesAndFolders = ListDir(path, "eng", true, &filesAndFolders);
-    filesAndFolders = ListDir(path, "ini", true, &filesAndFolders);
+    std::vector<bfs::path> filesAndFolders;
+    for(const auto ext : {"lst", "lbm", "bob", "idx", "bmp", "txt", "ger", "eng", "ini"})
+    {
+        std::vector<bfs::path> curFiles = ListDir(path, ext, true);
```
Comment (Flow86) [inline libs/s25main/Loader.cpp:1094]: result can be const (or simply const auto?)

File: libs/s25main/ogl/glTexturePacker.cpp [hunk 4]
```diff
@@ -97,7 +97,7 @@ bool glTexturePacker::packHelper(std::vector<glSmartBitmap*>& list)
             }
             // free texture packer, as it is not needed any more
             root->destroy(list.size());
```
Comment (Flow86) [inline libs/s25main/ogl/glTexturePacker.cpp:99]: is it possible to wrap that call into the node destructor itself?

File: tests/s25Main/locale/testLocalization.cpp [hunk 5]
```diff
@@ -34,7 +34,7 @@ struct LocaleFixture
     {
         rttr::test::LogAccessor logAcc;
         LANGUAGES.setLanguage("en");
-        LOADER.LoadFile(RTTRCONFIG.ExpandPath(FILE_PATHS[95]) + "/languages.ini", nullptr, true);
+        LOADER.Load(RTTRCONFIG.ExpandPath(FILE_PATHS[95]) + "/languages.ini", nullptr, true);
```
Comment (Flow86) [inline tests/s25Main/locale/testLocalization.cpp:37]: probably same here? to add the full path to the files-constants

File: libs/s25main/Loader.cpp (hunk 1 above)
Comment (Flamefire) [reply libs/s25main/Loader.cpp:291]: I am very much against that list of files because it's incredibly hard to work with especially as the indices into some array are used. This leads to things like `Load(FILEPATHS[2]); // foo.lst` which is bad for 2 reasons: Duplication of the name (in array and comment) and it can possibly become out of sync.

In the resourceLoading branch I have I started by adding the folders with resources to a registry and then load resources by plain resourceIDs (filename w/o any extension) which avoids the issues.

So I'd wait till we introduce something like that and not move even more into that array than there already is.

File: libs/s25main/ogl/glTexturePacker.cpp (hunk 4 above)
Comment (Flamefire) [reply libs/s25main/ogl/glTexturePacker.cpp:99]: No. The destroy function does a depth-first loop to destruct the tree. The dtor would do a breath-first recursive call likely killing the stack memory.

I was thinking about improving this but due to the tree-structure this packer is very slow and unusable in debug builds of MSVC (takes minutes to build the texture). Hence I'm planning to rewrite it using a flat allocation and less smart distribution strategy but which seems to be still very good

File: libs/s25main/Loader.cpp (hunk 3 above)
Comment (Flamefire) [reply libs/s25main/Loader.cpp:1094]: Good catch!

I'd only use auto where the type is mostly clear from the RHS or complicated (iterators) as IMO the type is a vital part for knowing the code.

File: libs/s25main/ogl/glTexturePacker.cpp (hunk 4 above)
Comment (Flow86) [reply libs/s25main/ogl/glTexturePacker.cpp:99]: ok :-)

File: libs/s25main/Loader.cpp (hunk 1 above)
Comment (Flow86) [reply libs/s25main/Loader.cpp:291]: yes but perhaps we can add some kind of FILE_PATH_FONTS_LST as a constant

File: libs/s25main/Loader.cpp (hunk 3 above)
Comment (Flow86) [reply libs/s25main/Loader.cpp]: yes I often do that too, but at least the const ;-)

Comment (Flamefire) [reply libs/s25main/Loader.cpp]: Done: https://github.com/Return-To-The-Roots/s25client/pull/1242/commits/c7e4b87cf09eb1d50f0fe7a2e50f518cae0690eb

File: libs/s25main/Loader.cpp (hunk 1 above)
Comment (Flamefire) [reply libs/s25main/Loader.cpp:291]: I don't see the advantage. IIRC this is only used once and the name of the constant is almost as long as the path. So I'd keep the changeset low and fix all those paths later.

Comment (Flow86) [reply libs/s25main/Loader.cpp:291]: the advantage is that we have all paths together in one file - so if we need to change them, we have them at one place

Comment (Flamefire) [reply libs/s25main/Loader.cpp:291]: Question then: Shouldn't that be a separate PR? This PR doesn't introduce new path constants so IMO this whole discussion is valuable but out of scope of this PR.

Comment (Flow86) [reply libs/s25main/Loader.cpp:291]: I like that commit. its okay if its a separate PR though

Comment (Flamefire) [reply libs/s25main/Loader.cpp:291]: Ok. Removed it from this PR so this can be merged now
