### PR TITLE
Fix Undefined Behaviour / RTTR_Assert triggering in nofShipWright

### LINKED ISSUE #1048: nofShipWright::nofShipWright SIGTRAP on sea map
I compiled s25client myself from git, commit ID 2f33ff0075597ff1310e0ba3954262fc1476a3d8 (should be current master). This is on debian buster/testing.

A few minutes after loading the [attached savegame](https://github.com/Return-To-The-Roots/s25client/files/2942214/Wasserwege.Auto.save.sav.gz), the game enters a debug trap. I attached gdb and obtained the following backtrace (no debug symbols unfortunately):

```
(gdb) bt
#0  0x00005555558c0b62 in nofShipWright::nofShipWright(Point<unsigned short>, unsigned char, nobUsual*) ()
#1  0x000055555587498d in JobFactory::CreateJob(Job, Point<unsigned short>, unsigned char, noRoadNode*) ()
#2  0x00005555557ed751 in nobBaseWarehouse::OrderJob(Job, noRoadNode*, bool) ()
#3  0x0000555555767543 in GamePlayer::FindWarehouseForJob(Job, noRoadNode*) ()
#4  0x0000555555766f66 in GamePlayer::AddJobWanted(Job, noRoadNode*) ()
#5  0x0000555555813953 in nobUsual::nobUsual(BuildingType, Point<unsigned short>, unsigned char, Nation) ()
#6  0x00005555558118f2 in nobShipYard::nobShipYard(Point<unsigned short>, unsigned char, Nation) ()
#7  0x000055555586e9fd in BuildingFactory::CreateBuilding(GameWorldBase&, BuildingType, Point<unsigned short>, unsigned c
#8  0x000055555588cab2 in nofBuilder::HandleDerivedEvent(unsigned int) ()
#9  0x0000555555877816 in noFigure::HandleEvent(unsigned int) ()
#10 0x000055555574c14c in EventManager::ExecuteEvents(std::_Rb_tree_iterator<std::pair<unsigned int const, std::__cxx11::
#11 0x000055555574c014 in EventManager::ExecuteCurrentEvents() ()
#12 0x000055555574bd7b in EventManager::ExecuteNextGF() ()
#13 0x0000555555755ed4 in Game::RunGF() ()
#14 0x000055555569a38e in GameClient::NextGF(bool) ()
#15 0x0000555555699ca4 in GameClient::ExecuteGameFrame() ()
#16 0x0000555555694294 in GameClient::Run() ()
#17 0x00005555555e8daf in GameManager::Run() ()
#18 0x00005555555d0ceb in RunProgram(boost::program_options::variables_map&) ()
#19 0x00005555555d117f in main ()
```

If there’s anything useful I could add, let me know.

### PR DESCRIPTION
**Pull request by horazont**
The assertion is unsafe at this point, even though it might
appear logical. The reason it is unsafe is that it is called from
nobShipYard::nobShipYard (the consturctor) indirectly through the
constructor nobUsual::nobUsual (constructor of the base class).

The dynamic_cast<nobShipYard*> then becomes undefined behaviour,
because the constructor of nobShipYard has not started to run on
the workplace object; it is still running the nobUsual
constructor.

See also https://stackoverflow.com/a/6299463/1248008

Fixes #1048.

### CODE REVIEW

**Comment by Flamefire** [comment]
You are correct. I'm just thinking *what*  the bug is. Technically the assertion is not wrong as it is an actual error to pass in anything but a shipyard. The rest of the class relies on that. IMO we should rather move the job ordering out of the constructor.

Idea:
- Buildings are added to the player anyway
- On adding of a nobUsual an order for that is placed

**Comment by horazont** [comment]
> Technically the assertion is not wrong as it is an actual error to pass in anything but a shipyard.

Ah yes, I was thinking that. Unfortunately, I don’t have the expertise in the codebase to follow through with the other suggestion.

> IMO we should rather move the job ordering out of the constructor.

I think this sounds very sane, also from a theoretical/architectural standpoint, but I’m quite the layman in this project ;-).

**Comment by Flamefire** [comment]
Fresh and sane ideas are always welcome. Often "outsiders"/laymans can provide valuable input for a project as they are not bound by "we have always done this".

Anyway thanks a lot for finding the issue. If you don't want to try taking the above, I'll take it over

**Comment by horazont** [comment]
Go ahead, since I can’t make any promises :). I might come back to this issue if I have some time to spare to further develop it if there hasn’t been any progress.

**Comment by horazont** [comment]
Ok, nevermind. I took another stab at the issue, it was much less complicated than I anticipated—but of course, I might’ve gone the entire wrong way to do this :).

Thanks for taking a look.

File: libs/s25main/factories/BuildingFactory.cpp [hunk 1]
```diff
@@ -42,6 +43,17 @@ noBuilding* BuildingFactory::CreateBuilding(GameWorldBase& gwg, const BuildingTy
         case BLD_SHIPYARD: bld = new nobShipYard(pt, player, nation); break;
         default: bld = new nobUsual(type, pt, player, nation); break;
     }
+    GamePlayer &player_obj = gwg.GetPlayer(player);
```
Comment (Flamefire) [inline libs/s25main/factories/BuildingFactory.cpp]: Could you move this either below the `AddBuilding` (and reuse player_obj, btw: `lowerCamelCase` please) or into `GamePlayer::AddBuilding`? I think the latter is the better place ( I don't like doing to much in the factory, actually it should just create the building and nothing else)

File: libs/s25main/buildings/nobUsual.cpp [hunk 2]
```diff
@@ -49,7 +49,6 @@ nobUsual::nobUsual(BuildingType type, MapPoint pos, unsigned char player, Nation
 
     // Arbeiter bestellen
```
Comment (Flamefire) [inline libs/s25main/buildings/nobUsual.cpp]: Remove comment and move owner definition down before first use

File: libs/s25main/factories/BuildingFactory.cpp [hunk 3]
```diff
@@ -42,6 +43,17 @@ noBuilding* BuildingFactory::CreateBuilding(GameWorldBase& gwg, const BuildingTy
...
+    const auto &description = BLD_WORK_DESC[type];
+    // We're filtering out JOB_PRIVATE because military buildings do their own
+    // worker stuff.
+    // We also can't do this in the nobUsual constructor, because at the point
+    // the respective nof* object is created through JobFactory, the building
+    // would not be fully initialized yet (which may invoke undefined
+    // behaviour).
+    if (description.job != JOB_NOTHING && description.job != JOB_PRIVATE) {
+        player_obj.AddJobWanted(BLD_WORK_DESC[type].job, bld);
```
Comment (Flamefire) [inline libs/s25main/factories/BuildingFactory.cpp]: use `description.job` please ;)

**Comment by horazont** [comment]
I think I addressed all comments; I made a quick test by building up to a Shipyard and it seems good! :)

File: libs/s25main/factories/BuildingFactory.cpp [hunk 4]
```diff
@@ -43,8 +44,19 @@ noBuilding* BuildingFactory::CreateBuilding(GameWorldBase& gwg, const BuildingTy
         default: bld = new nobUsual(type, pt, player, nation); break;
     }
     gwg.SetNO(pt, bld);
+    GamePlayer &playerObject = gwg.GetPlayer(player);
     // Don't do this in ctor as building might not be fully initialized yet
-    gwg.GetPlayer(player).AddBuilding(bld, type);
+    playerObject.AddBuilding(bld, type);
+    const auto &description = BLD_WORK_DESC[type];
+    // We're filtering out JOB_PRIVATE because military buildings do their own
```
Comment (Flamefire) [inline libs/s25main/factories/BuildingFactory.cpp]: Put on 1 line

File: libs/s25main/factories/BuildingFactory.cpp [hunk 5]
```diff
@@ -43,8 +44,19 @@ noBuilding* BuildingFactory::CreateBuilding(GameWorldBase& gwg, const BuildingTy
...
+    // worker stuff.
+    // We also can't do this in the nobUsual constructor, because at the point
```
Comment (Flamefire) [inline libs/s25main/factories/BuildingFactory.cpp]: Remove as already covered by line 46/48

**Comment by Flamefire** [comment]
Good, just a minor nitpick.

When you are done, please rebase on current master (pull master, rebase your branch, force push your branch) so github does not show the "out-of-date" message

File: libs/s25main/factories/BuildingFactory.cpp (hunk 5 above)
Comment (horazont) [reply libs/s25main/factories/BuildingFactory.cpp]: I’d like to replace the comment in line 46/48 then, because I think my comment is more useful. What do you think?

File: libs/s25main/factories/BuildingFactory.cpp (hunk 4 above)
Comment (horazont) [reply libs/s25main/factories/BuildingFactory.cpp]: Is there documentation on the maximum line length acceptable in comments in this project?

**Comment by horazont** [comment]
There we go, hopefully!

**Comment by horazont** [comment]
> Idea:
> 
>     * Buildings are added to the player anyway
> 
>     * On adding of a nobUsual an order for that is placed

Hm, do you prefer the way of handling the Job in AddBuilding? I think doing it in AddBuilding (instead of what I’m doing here now) would be cleaner. If you agree, I’ll change it to do the job ordering in AddBuilding (which already does things based on the type of building).

**Comment by Flamefire** [comment]
> Hm, do you prefer the way of handling the Job in AddBuilding? I think doing it in AddBuilding (instead of what I’m doing here now) would be cleaner. If you agree, I’ll change it to do the job ordering in AddBuilding (which already does things based on the type of building).

Yes, go ahead :)

**Comment by horazont** [comment]
There we go, finally, hopefully :)

File: libs/s25main/factories/BuildingFactory.cpp (hunk 4 above)
Comment (Flamefire) [reply libs/s25main/factories/BuildingFactory.cpp]: There is a .clang-format file and a `make clangFormat` target so don't worry about it, just don't manually break it and run the target. Length should be 120 or so.

**Comment by horazont** [comment]
Ran clangFormat, it made some whitespace changes and re-ordered the includes.
