### PR TITLE
Drawing improvements

### LINKED ISSUE #585: Lobby chat notification color
When hosting a server there is the lobby chat and the game chat.
When you get a message, the buttons are blinking - sadly they use the wrong texture, currently IO id 8 is used but should be IO id 3.

Just have a look at the "Lobby Chat" button and "Return"

lobbychat

### PR DESCRIPTION
**Pull request by Flamefire**
This refactors lots of drawing related code and adds some tests.
Main points:

- Test screen added for visual tests (double click version text on main screen to enter)
- button up/down state improved (no more artefacts on pressed button)
- illuminate also borderless buttons
- deepening control now has a base class and textdeepening does not inherit from ctrlText (as it isn't a ctrlText)
- add function to get text bounds and use it to implement getting element bounds
- Will add button blinking to fix #585

### CODE REVIEW

File: src/Window.h [hunk 1]
```diff
@@ -216,7 +216,7 @@ class Window
         // GUI-Notify-Messages
 
         // Nachrichten, die von oben (WindowManager) nach unten (zu Controls) gereicht werden
-        virtual void Msg_PaintBefore(){}
+        virtual void Msg_PaintBefore();
```
Comment (Flow86) [inline src/Window.h]: override?

File: src/desktops/dskHostGame.cpp [hunk 2]
```diff
@@ -431,6 +431,7 @@ void dskHostGame::UpdatePlayerRow(const unsigned row)
  */
 void dskHostGame::Msg_PaintBefore()
 {
+    Desktop::Msg_PaintBefore();
```
Comment (Flow86) [inline src/desktops/dskHostGame.cpp]: evtl sollten wir allgemein eine art typedef base in den klassen machen, dann kann man immer "base::..." schreiben?

File: src/Window.h (hunk 1 above)
Comment (Flamefire) [inline src/Window.h]: This is the base class ;-)

File: src/desktops/dskHostGame.cpp (hunk 2 above)
Comment (Flamefire) [inline src/desktops/dskHostGame.cpp]: Yes, I've been thinking about this. Especially when you change the inheritance to introduce another level this would prove very helpful. However it would be a lot of work.

File: src/Window.h (hunk 1 above)
Comment (Flow86) [inline src/Window.h]: oh ;-)

File: src/desktops/dskHostGame.cpp (hunk 2 above)
Comment (Flow86) [inline src/desktops/dskHostGame.cpp]: > However it would be a lot of work.
one line per class?

Comment (Flamefire) [inline src/desktops/dskHostGame.cpp]: Yep. For 40 classes or so. Its just boring ;)
I see if I can make a regex or so to do this automatically. We need it for the gameobjects too to get rid of all the `Destroy_xxx` functions and the like
